//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int client_id { get; set; }
        public int invoice_id { get; set; }
        public string products { get; set; }
        public decimal total { get; set; }
    
        public virtual client client { get; set; }
    }
}
