//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping
    {
        public int shopping_id { get; set; }
        public string products { get; set; }
        public int client_id { get; set; }
        public int category_id { get; set; }
        public int type_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual client client { get; set; }
        public virtual type type { get; set; }
    }
}
